Ansible 4
Otus-DevOps-2018-05/n3tdom_infra pull request #10
Opened 2018-09-03 20:12 UTC by n3tdom

# Выполнено ДЗ №

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Работа с Vagrant 
- Molecule (virtualenv)

Самостоятельное задание:
1. Прописан тест на порт mongo в test_default.py
2. Пакер теперь использует packer_db.yml -> роль db
packer validate -var-file=./packer/variables.json ./packer/db.json

## Как запустить проект:
Vagrant: 
vagrant up

Molecule:
molecule init scenario --scenario-name default -r db -d vagrant

## Как проверить работоспособность:
 - Например, перейти по ссылке http:/10.10.10.20:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-09-03 21:30 UTC, n3tdom commented
Не понятно как вылечить конфликт, нужна помощь =\

2018-09-25 13:12 UTC, WeitBelou commented
> Не понятно как вылечить конфликт, нужна помощь =\

Отребейзил, проверь, пожалуйста, что ничего не потерялось

2018-09-25 13:12 UTC, grim-yawn requested changes
Нужно проверить ребейз

2018-09-25 13:25 UTC, grim-yawn requested changes
Нужно проверить ребейз

2018-09-27 15:22 UTC, bytemux commented
@WeitBelou получилось исправить через merge

2018-10-19 12:26 UTC, grim-yawn approved these changes

2018-10-22 09:06 UTC, merged