Ansible 1
Otus-DevOps-2018-05/n3tdom_infra pull request #7
Opened 2018-08-02 15:33 UTC by n3tdom

# Выполнено ДЗ ansible-1

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
Установлен ansible, заполнен простой плейбук инвентарь в виде .yml , .ini

### Плейбук
После rm директории плейбук отрабатывает, а не просто сообщает о том что репозиторий уже склонирован, поэтому статус меняется на changed

### Задание со * #1 
Создан файл inventory.json по последнему примеру отсюда https://docs.ansible.com/ansible/latest/dev_guide/developing_inventory.html

Так как по заданию нам хватит статической конфигурации, написан простой скрипт по команде inventory.sh --list выдающий исходный inventory.json

## Как запустить проект:
ansible all -m ping -i inventory.sh 

## Как проверить работоспособность:
ansible-inventory --graph -i inventory.sh

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2018-08-08 14:56 UTC, WeitBelou commented
Привет. В общем всё ок. Есть пара небольших замечаний.

2018-08-08 15:00 UTC, grim-yawn requested changes

2018-08-08 15:00 UTC, grim-yawn commented on ansible/inventory.json
> +        "ungrouped": {
ungrouped можно не указывать. И вообще всё пустое можно опустить (e.g. children).

2018-08-08 15:00 UTC, grim-yawn commented on ansible/inventory.json
> +        "all": {
Вот тут тоже можно опустить all, так как добавится по умолчанию в all

2018-08-08 15:00 UTC, grim-yawn commented on ansible/inventory.sh
> +#launch example ./get-inventory.sh --list
Вот тут можно подчистить debug и поправить название скрипта в комменте

2018-08-08 15:00 UTC, grim-yawn commented on ansible/inventory.sh
> +# Not implemented
Я бы сделал чуть более строгий выход (условный exit -1)

2018-08-13 14:39 UTC, grim-yawn approved these changes

2018-09-03 16:59 UTC, merged

2018-09-03 16:59 UTC, n3tdom commented
Поправил замечания, спасибо!